---
- name: Maintenance on TSE
  hosts: all

#  vars_prompt:
#    - name: "Message"
#      prompt: "Entrez votre message"
#      private: no
#      default: "localhost"

ansible_ssh_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore


  vars:
      Message: Toto

  tasks:
  - name: Ping TSE
    win_ping:

  - name: send msg
    win_shell: msg.exe /server:localhost * "{{ Message }}"
